version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: quiz-laravel
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - quiz_network
        ports:
            - "8000:80"
        environment:
            - DB_HOST=db
            - DB_DATABASE=quiz_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - APP_ENV=local
            - APP_DEBUG=true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    db:
        image: mysql:8
        container_name: quiz-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: quiz_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: quiz_user
            MYSQL_PASSWORD: quiz_pass
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - quiz_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        container_name: quiz-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - quiz_network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis-admin:
        image: rediscommander/redis-commander:latest
        container_name: quiz-redis-admin
        restart: unless-stopped
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        networks:
            - quiz_network
        depends_on:
            - redis

networks:
    quiz_network:

volumes:
    db_data:
